---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-demo-app
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn: []
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./manifests/apps/nginx-demo-app
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: iso-cache-app
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn: []
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./manifests/apps/iso-cache-app
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lars-media-app
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn: []
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./manifests/apps/lars-media-app
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metro-app
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn: []
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: cluster-key
  path: ./manifests/apps/metro-app
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: computater-app
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn: []
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./manifests/apps/computater-app
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: info-portal-app
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn: []
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./manifests/apps/info-portal-app
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: adventofcode-app
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn: []
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: cluster-key
  path: ./manifests/apps/adventofcode-app
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hytale-app
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn: []
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./manifests/apps/hytale-app
  prune: true
  wait: true
  timeout: 5m0s
