apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./authentication.yaml
  - ./storage-class.yaml
  - ./driver/rbac.yaml
  - ./driver/driver.yaml
  - ./driver/controller.yaml
  - ./driver/node.yaml
