apiVersion: apps/v1
kind: Deployment
metadata:
  name: lars-media-app
  namespace: lars-media-app
  annotations:
    configmap.reloader.stakater.com/reload: config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lars-media-app
  template:
    metadata:
      labels:
        app: lars-media-app
    spec:
      containers:
        - name: media-app
          image: ghcr.io/kubeside/images/media-app@sha256:87fac7e5720d49698330b00d443b955274b698297743e6f54e008640b7dad8de
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /var/www/html/config.json
              subPath: config.json
              readOnly: true
            - name: static
              mountPath: /var/www/html/static 
              readOnly: true       
      volumes:
        - name: config
          configMap:
            name: config
            items:
              - key: config.json
                path: config.json
        - name: static
          persistentVolumeClaim:
            claimName: assets
        
