apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: hytale
  namespace: hytale-app
spec:
  blocks:
    - cidr: 10.4.0.51/32
  serviceSelector:
    matchLabels:
      io.kubernetes.service.namespace: "hytale-app"

