apiVersion: v1
kind: Service
metadata:
  name: hytale
  namespace: hytale-app
spec:
  selector:
    app: hytale
  ports:
    - protocol: UDP
      port: 5520
      targetPort: 5520
  type: LoadBalancer
