apiVersion: v1
kind: Secret
metadata:
    name: backend-config
    namespace: adventofcode-app
stringData:
    config.json: ENC[AES256_GCM,data:3z+dy2NVM9C+7+lGTME9sHemGg2aDxx2QlF+3GtS8F6Ot89x0rtBb+mYJcwNmA69ulk7zJ8KJ/8Q658DwNhB+kYuf6Wx5Wn2omBZSzQT1fPvD9n1+hs56WBHvawNKUfeTnx6tKHTfGINAUpng0G/XdsTZs7tL9UTs0xkDuew4RsX36Fzh9sQYV/8OK7A8z8DbGa4x1305vOXn+aP6TIUy5eajIR9xIrsfKj5DGjiZN6JvT9veAaU,iv:z4G2CKM1zCAuRmn8jKRm47BXCtphg4K9K8Poe2x6iO8=,tag:p1pbZUUSF2NGC2rJB8DWjA==,type:str]
sops:
    age:
        - recipient: age15h69z4sdwl8teyzuttaldhaaadmfzmmjkvszw0ar6sdq5ryhjp3qwagxgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2eTBMS2l4U2JESFNiUldX
            bUJVTHBrdTlZREFGR2ttZDZzMitRYmplNWhzCjJVZUM4enZOUjh2eGlnVjJISGNB
            aUhqRWxkQjFYdEFaMitjYmVaOUtpYTQKLS0tIGN4Z2pBOVRoNkVRUTB6NDVETmgv
            SElUV1ExNHZvbnVxMCtkNG1sOGpFcEkKMEqsmhfWWsKwL20MISge0sLUVrIkvEcZ
            SnE7F7fBAhsSTUwQmkCyn5UHSPKuQDzu52Sft4vmQ9HG/lqIch7h0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T16:51:22Z"
    mac: ENC[AES256_GCM,data:JZ3opUZ/1yFozZOkxbCW2cqjXI4K/Hy+r7znt3A6ExOKKPr+j8T1HaxJ1XV+UhG+G4GXHoYi7AG4EMBIZVDLhTJn4y8z9xR5lczKMXV7EJgHVoWB39QnbqWFY9wfJk7eLcvX8bZKliSvtI05bkhuzwvrtt/LTBI7obDQkHU7faA=,iv:1mJgsjipfQjp4OB2jfm+j0s2ZwzkLZImhqvxAZyS2cI=,tag:p6hhCDfjiiRQozQ51KhaPw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
